version: '3.7'
services:
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    restart: unless-stopped
    environment:
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - .:/app
      - /app/tmp
    links:
      - mysql
      - redis
      - clickhouse
    stdin_open: true
    tty: true
  redis:
    image: redis:5.0.5-alpine
    restart: unless-stopped
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  clickhouse:
    image: yandex/clickhouse-server:19.14
    restart: unless-stopped
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
  grafana:
    image: grafana/grafana:6.4.1
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 7000:3000
volumes:
  mysql-db:
