{
 "title": "Item prices analyzer",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "By quality (amount)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as time,\n    quality,\n    count() as amount\nFROM $table\nWHERE $timeFilter\nGROUP BY time, quality\nORDER BY time, amount",
     "round": "0s",
     "table": "item_prices"
    }
   ]
  },
  {
   "title": "By rarity amount (items amount)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as time,\n    rarity,\n    count() as amount\nFROM $table\nWHERE $timeFilter\nGROUP BY time, rarity\nORDER BY time, amount",
     "round": "0s",
     "table": "item_prices"
    }
   ]
  },
  {
   "title": "By rarity (instant sale price)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as time,\n    rarity as rarity,\n    AVG(instant_sale_price)\nFROM $table\nWHERE $timeFilter\nGROUP BY time, rarity\nORDER BY time, rarity",
     "round": "0s",
     "table": "item_prices"
    }
   ]
  },
  {
   "title": "By rarity (average price)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as time,\n    rarity as rarity,\n    AVG(price)\nFROM $table\nWHERE $timeFilter\nGROUP BY time, rarity\nORDER BY time, rarity",
     "round": "0s",
     "table": "item_prices"
    }
   ]
  }
 ]
}